GET http://127.0.0.1:8088/hello?name=zhangsan
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Accept-Encoding: br,deflate,gzip,x-gzip

###
GET http://127.0.0.1:8088/data
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Accept-Encoding: br,deflate,gzip,x-gzip


###
POST http://127.0.0.1:8088/user/register
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Accept-Encoding: br,deflate,gzip,x-gzip
Content-Type: application/json

{
  "name":"lisi",
  "loginType": "1",
  "email": "baozhongmail@yeah.net"
}

###
GET http://127.0.0.1:8088/food/nearby?Latitude=37.7865580501799&Longitude=-122.40103337534973&distance=10
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Accept-Encoding: br,deflate,gzip,x-gzip



